"""Mười chín đơn tuyển dụng mẫu.

Dùng cho môi trường phát triển và buổi bảo vệ, cho đến khi doanh nghiệp nhập đơn
thật qua file Excel. Bộ dữ liệu này được chọn để **chứng minh bộ đối chiếu chạy
đúng**, nên phủ có chủ ý:

- đủ ba diện chương trình và ba loại hình cơ sở;
- sáu vùng tại Nhật, để thấy điểm cộng khác nhau giữa trùng tỉnh và trùng vùng;
- yêu cầu tiếng Nhật trải từ N5 đến N3, để một hồ sơ N4 vừa đạt đơn này vừa
  trượt đơn kia — không có sự tương phản đó thì không chứng minh được bộ lọc
  cứng có hoạt động hay không;
- vài đơn yêu cầu kinh nghiệm hoặc giới hạn giới tính, là hai tiêu chí hay làm
  ứng viên bị loại trong thực tế;
- ba đơn không hiện trên website vì ba lý do khác nhau (nháp, tạm dừng, quá hạn),
  để kiểm tra bộ lọc công khai chứ không chỉ tin là nó đúng.

Hạn nộp ghi theo số ngày kể từ hôm nay thay vì ngày cố định, để bộ dữ liệu không
tự hết hạn sau vài tuần và làm hỏng bản demo.
"""

# Mỗi phần tử là dạng "người đọc được"; script seed sẽ chuẩn hóa và bổ sung
# vùng, mã đơn và các trường hệ thống.
JOB_ORDERS_SEED: list[dict] = [
    {
        "title": "Điều dưỡng viện dưỡng lão Tokyo",
        "employer_name": "Viện dưỡng lão Sakura",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Tokyo",
        "city": "Setagaya",
        "quota": 5,
        "deadline_in_days": 78,
        "japanese_required": "N4",
        "education_required": "cao_dang",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 195000,
        "salary_max": 215000,
        "allowances": ["Hỗ trợ ký túc xá", "Phụ cấp ca đêm", "Phụ cấp đi lại"],
        "cost_total_vnd": 110_000_000,
        "interview_in_days": 30,
        "departure_expected": "2027-03",
        "highlights": [
            "Cơ sở mới xây, trang thiết bị hiện đại",
            "Có nhân viên người Việt hỗ trợ năm đầu",
        ],
        "description": "Chăm sóc sinh hoạt hằng ngày cho người cao tuổi tại viện dưỡng lão quy mô 90 giường.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng bệnh viện Yokohama",
        "employer_name": "Bệnh viện Yokohama Chuo",
        "employer_type": "benh_vien",
        "program": "epa",
        "prefecture": "Kanagawa",
        "city": "Yokohama",
        "quota": 3,
        "deadline_in_days": 93,
        "japanese_required": "N3",
        "education_required": "cao_dang",
        "experience_min": 1,
        "age_min": 21,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 180000,
        "salary_max": 200000,
        "allowances": ["Ký túc xá miễn phí", "Hỗ trợ học tiếng Nhật"],
        "cost_total_vnd": 35_000_000,
        "interview_in_days": 45,
        "departure_expected": "2027-04",
        "highlights": [
            "Diện EPA, chi phí thấp",
            "Được hỗ trợ ôn thi chứng chỉ quốc gia Nhật Bản",
        ],
        "description": "Hỗ trợ điều dưỡng tại khoa nội, làm việc theo ca cùng điều dưỡng viên người Nhật.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Hộ lý chăm sóc tại gia Saitama",
        "employer_name": "Himawari Home Care",
        "employer_type": "cham_soc_tai_gia",
        "program": "thuc_tap_sinh",
        "prefecture": "Saitama",
        "city": "Kawagoe",
        "quota": 10,
        "deadline_in_days": 48,
        "japanese_required": "N5",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 18,
        "age_max": 30,
        "gender_pref": "nu",
        "salary_min": 160000,
        "salary_max": 170000,
        "allowances": ["Hỗ trợ tiền nhà", "Phụ cấp chuyên cần"],
        "cost_total_vnd": 95_000_000,
        "interview_in_days": 21,
        "departure_expected": "2027-02",
        "highlights": ["Không yêu cầu kinh nghiệm", "Tuyển số lượng lớn"],
        "description": "Đến nhà người cao tuổi hỗ trợ vệ sinh, ăn uống và vận động theo lịch được phân công.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Chiba",
        "employer_name": "Viện dưỡng lão Kaikou",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Chiba",
        "city": "Funabashi",
        "quota": 6,
        "deadline_in_days": 129,
        "japanese_required": "N4",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 38,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 190000,
        "salary_max": 205000,
        "allowances": ["Hỗ trợ ký túc xá", "Phụ cấp ca đêm"],
        "cost_total_vnd": 105_000_000,
        "interview_in_days": 40,
        "departure_expected": "2027-05",
        "highlights": ["Nhận ứng viên trung cấp", "Khoảng tuổi rộng"],
        "description": "Chăm sóc người cao tuổi tại cơ sở lưu trú dài hạn, có xe đưa đón nhân viên.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Osaka",
        "employer_name": "Viện dưỡng lão Naniwa",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Osaka",
        "city": "Higashiosaka",
        "quota": 8,
        "deadline_in_days": 109,
        "japanese_required": "N4",
        "education_required": "cao_dang",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 185000,
        "salary_max": 200000,
        "allowances": ["Hỗ trợ ký túc xá", "Bao ăn ca"],
        "cost_total_vnd": 100_000_000,
        "interview_in_days": 35,
        "departure_expected": "2027-04",
        "highlights": ["Cộng đồng người Việt đông", "Chi phí sinh hoạt vừa phải"],
        "description": "Làm việc tại viện dưỡng lão 70 giường, ca ngày và ca đêm luân phiên.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng bệnh viện Kyoto",
        "employer_name": "Bệnh viện Kyoto Daiichi",
        "employer_type": "benh_vien",
        "program": "epa",
        "prefecture": "Kyoto",
        "city": "Kyoto",
        "quota": 2,
        "deadline_in_days": 68,
        "japanese_required": "N3",
        "education_required": "dai_hoc",
        "experience_min": 2,
        "age_min": 22,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 190000,
        "salary_max": 210000,
        "allowances": ["Ký túc xá giá ưu đãi", "Hỗ trợ thi chứng chỉ"],
        "cost_total_vnd": 30_000_000,
        "interview_in_days": 25,
        "departure_expected": "2027-04",
        "highlights": ["Yêu cầu cao nhưng chi phí thấp", "Môi trường bệnh viện lớn"],
        "description": "Hỗ trợ điều dưỡng tại bệnh viện đa khoa, ưu tiên ứng viên có kinh nghiệm lâm sàng.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Hộ lý viện dưỡng lão Kobe",
        "employer_name": "Viện dưỡng lão Kobe Midori",
        "employer_type": "vien_duong_lao",
        "program": "thuc_tap_sinh",
        "prefecture": "Hyogo",
        "city": "Kobe",
        "quota": 12,
        "deadline_in_days": 58,
        "japanese_required": "N5",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 18,
        "age_max": 32,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 158000,
        "salary_max": 168000,
        "allowances": ["Ký túc xá gần nơi làm việc", "Phụ cấp chuyên cần"],
        "cost_total_vnd": 90_000_000,
        "interview_in_days": 20,
        "departure_expected": "2027-03",
        "highlights": ["Tuyển nhiều", "Yêu cầu tiếng Nhật ở mức cơ bản"],
        "description": "Hỗ trợ sinh hoạt cho người cao tuổi, có người hướng dẫn trong ba tháng đầu.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Nagoya",
        "employer_name": "Viện dưỡng lão Nagoya Hikari",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Aichi",
        "city": "Nagoya",
        "quota": 10,
        "deadline_in_days": 168,
        "japanese_required": "N4",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 40,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 185000,
        "salary_max": 200000,
        "allowances": ["Hỗ trợ ký túc xá", "Phụ cấp ca đêm", "Thưởng hai kỳ"],
        "cost_total_vnd": 100_000_000,
        "interview_in_days": 55,
        "departure_expected": "2027-06",
        "highlights": ["Khoảng tuổi rộng nhất trong các đơn đang tuyển", "Có thưởng hai kỳ"],
        "description": "Chăm sóc người cao tuổi tại cơ sở thuộc tập đoàn y tế lớn vùng Chubu.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Hộ lý chăm sóc tại gia Shizuoka",
        "employer_name": "Fuji Care",
        "employer_type": "cham_soc_tai_gia",
        "program": "thuc_tap_sinh",
        "prefecture": "Shizuoka",
        "city": "Hamamatsu",
        "quota": 8,
        "deadline_in_days": 83,
        "japanese_required": "N5",
        "education_required": None,
        "experience_min": 0,
        "age_min": 18,
        "age_max": 30,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 155000,
        "salary_max": 165000,
        "allowances": ["Hỗ trợ tiền nhà"],
        "cost_total_vnd": 85_000_000,
        "interview_in_days": 28,
        "departure_expected": "2027-03",
        "highlights": ["Không yêu cầu bằng cấp chuyên ngành", "Chi phí thấp nhất nhóm thực tập sinh"],
        "description": "Hỗ trợ chăm sóc tại nhà, di chuyển giữa các hộ trong khu vực bằng xe đạp điện.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng bệnh viện Nagano",
        "employer_name": "Bệnh viện Nagano Kosei",
        "employer_type": "benh_vien",
        "program": "epa",
        "prefecture": "Nagano",
        "city": "Nagano",
        "quota": 3,
        "deadline_in_days": 119,
        "japanese_required": "N3",
        "education_required": "cao_dang",
        "experience_min": 1,
        "age_min": 21,
        "age_max": 34,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 175000,
        "salary_max": 195000,
        "allowances": ["Ký túc xá miễn phí", "Phụ cấp vùng lạnh"],
        "cost_total_vnd": 35_000_000,
        "interview_in_days": 50,
        "departure_expected": "2027-05",
        "highlights": ["Chi phí thấp", "Khí hậu mát mẻ, gần khu nghỉ dưỡng"],
        "description": "Hỗ trợ điều dưỡng tại bệnh viện tuyến tỉnh, môi trường làm việc ít áp lực.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Fukuoka",
        "employer_name": "Viện dưỡng lão Hakata",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Fukuoka",
        "city": "Fukuoka",
        "quota": 6,
        "deadline_in_days": 98,
        "japanese_required": "N4",
        "education_required": "cao_dang",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 180000,
        "salary_max": 195000,
        "allowances": ["Hỗ trợ ký túc xá", "Bao ăn ca"],
        "cost_total_vnd": 98_000_000,
        "interview_in_days": 38,
        "departure_expected": "2027-04",
        "highlights": ["Chi phí sinh hoạt thấp", "Gần sân bay quốc tế"],
        "description": "Chăm sóc người cao tuổi tại cơ sở trung tâm thành phố Fukuoka.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Hộ lý viện dưỡng lão Kumamoto",
        "employer_name": "Viện dưỡng lão Aso",
        "employer_type": "vien_duong_lao",
        "program": "thuc_tap_sinh",
        "prefecture": "Kumamoto",
        "city": "Kumamoto",
        "quota": 15,
        "deadline_in_days": 183,
        "japanese_required": "N5",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 18,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 152000,
        "salary_max": 162000,
        "allowances": ["Ký túc xá miễn phí", "Phụ cấp chuyên cần"],
        "cost_total_vnd": 88_000_000,
        "interview_in_days": 60,
        "departure_expected": "2027-07",
        "highlights": ["Số lượng tuyển lớn nhất", "Hạn nộp còn dài"],
        "description": "Chăm sóc người cao tuổi tại cơ sở vùng ngoại ô, môi trường yên tĩnh.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng bệnh viện Nagasaki",
        "employer_name": "Bệnh viện Nagasaki Kinen",
        "employer_type": "benh_vien",
        "program": "epa",
        "prefecture": "Nagasaki",
        "city": "Nagasaki",
        "quota": 2,
        "deadline_in_days": 73,
        "japanese_required": "N3",
        "education_required": "dai_hoc",
        "experience_min": 1,
        "age_min": 22,
        "age_max": 33,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 178000,
        "salary_max": 198000,
        "allowances": ["Ký túc xá giá ưu đãi", "Hỗ trợ thi chứng chỉ"],
        "cost_total_vnd": 32_000_000,
        "interview_in_days": 30,
        "departure_expected": "2027-05",
        "highlights": ["Diện EPA", "Số lượng ít, cạnh tranh cao"],
        "description": "Hỗ trợ điều dưỡng tại bệnh viện chuyên khoa, yêu cầu bằng đại học điều dưỡng.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Sapporo",
        "employer_name": "Viện dưỡng lão Sapporo Yuki",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Hokkaido",
        "city": "Sapporo",
        "quota": 4,
        "deadline_in_days": 140,
        "japanese_required": "N4",
        "education_required": "trung_cap",
        "experience_min": 1,
        "age_min": 20,
        "age_max": 38,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 175000,
        "salary_max": 190000,
        "allowances": ["Ký túc xá có sưởi", "Phụ cấp vùng lạnh"],
        "cost_total_vnd": 95_000_000,
        "interview_in_days": 48,
        "departure_expected": "2027-06",
        "highlights": ["Phụ cấp vùng lạnh", "Yêu cầu một năm kinh nghiệm"],
        "description": "Chăm sóc người cao tuổi tại cơ sở ở Sapporo, có hỗ trợ chi phí mùa đông.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Điều dưỡng chăm sóc tại gia Hiroshima",
        "employer_name": "Hiroshima Heiwa Care",
        "employer_type": "cham_soc_tai_gia",
        "program": "tokutei_ginou",
        "prefecture": "Hiroshima",
        "city": "Hiroshima",
        "quota": 3,
        "deadline_in_days": 88,
        "japanese_required": "N3",
        "education_required": "cao_dang",
        "experience_min": 1,
        "age_min": 21,
        "age_max": 36,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 200000,
        "salary_max": 225000,
        "allowances": ["Phụ cấp đi lại", "Thưởng hiệu suất"],
        "cost_total_vnd": 105_000_000,
        "interview_in_days": 33,
        "departure_expected": "2027-05",
        "highlights": ["Mức lương cao nhất nhóm chăm sóc tại gia", "Yêu cầu tiếng Nhật N3"],
        "description": "Chăm sóc tại nhà cho khách hàng cao cấp, yêu cầu giao tiếp tốt bằng tiếng Nhật.",
        "status": "open",
        "published": True,
    },
    {
        "title": "Hộ lý viện dưỡng lão Sendai",
        "employer_name": "Viện dưỡng lão Sendai Aoba",
        "employer_type": "vien_duong_lao",
        "program": "thuc_tap_sinh",
        "prefecture": "Miyagi",
        "city": "Sendai",
        "quota": 10,
        "deadline_in_days": 12,
        "japanese_required": "N5",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 18,
        "age_max": 30,
        "gender_pref": "nu",
        "salary_min": 150000,
        "salary_max": 160000,
        "allowances": ["Ký túc xá miễn phí"],
        "cost_total_vnd": 85_000_000,
        "interview_in_days": 8,
        "departure_expected": "2027-02",
        "highlights": ["Sắp hết hạn nộp hồ sơ", "Phỏng vấn sớm"],
        "description": "Chăm sóc người cao tuổi tại cơ sở trung tâm Sendai. Đơn sắp đóng, ưu tiên hồ sơ nộp sớm.",
        "status": "open",
        "published": True,
    },
    # --- Ba đơn dưới đây cố ý không hiện trên website, mỗi đơn một lý do khác nhau ---
    {
        "title": "Điều dưỡng cao cấp Shinjuku",
        "employer_name": "Viện dưỡng lão Shinjuku Premium",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Tokyo",
        "city": "Shinjuku",
        "quota": 2,
        "deadline_in_days": -20,
        "japanese_required": "N3",
        "education_required": "cao_dang",
        "experience_min": 2,
        "age_min": 23,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 220000,
        "salary_max": 240000,
        "allowances": ["Phụ cấp trung tâm thành phố", "Thưởng hai kỳ"],
        "cost_total_vnd": 120_000_000,
        "interview_in_days": -30,
        "departure_expected": "2027-01",
        "highlights": ["Mức lương cao nhất", "Đã quá hạn nộp hồ sơ"],
        "description": "Đơn đã quá hạn nộp. Giữ lại để kiểm tra bộ lọc công khai loại đúng đơn hết hạn.",
        "status": "open",
        "published": True,
        "internal_note": "Đơn mẫu: quá hạn nhưng vẫn bật công khai, dùng để kiểm tra bộ lọc.",
    },
    {
        "title": "Điều dưỡng bệnh viện Osaka Minami",
        "employer_name": "Bệnh viện Osaka Minami",
        "employer_type": "benh_vien",
        "program": "epa",
        "prefecture": "Osaka",
        "city": "Osaka",
        "quota": 3,
        "deadline_in_days": 156,
        "japanese_required": "N3",
        "education_required": "cao_dang",
        "experience_min": 1,
        "age_min": 21,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 185000,
        "salary_max": 205000,
        "allowances": ["Ký túc xá miễn phí"],
        "cost_total_vnd": 33_000_000,
        "interview_in_days": 65,
        "departure_expected": "2027-06",
        "highlights": ["Đang soạn thảo, chưa công bố"],
        "description": "Đơn còn ở trạng thái nháp, dùng để thử thao tác công bố trên màn hình quản trị.",
        "status": "draft",
        "published": False,
        "internal_note": "Đơn mẫu: còn nháp, chờ đối tác xác nhận số lượng.",
    },
    {
        "title": "Điều dưỡng viện dưỡng lão Kamakura",
        "employer_name": "Viện dưỡng lão Kamakura",
        "employer_type": "vien_duong_lao",
        "program": "tokutei_ginou",
        "prefecture": "Kanagawa",
        "city": "Kamakura",
        "quota": 4,
        "deadline_in_days": 124,
        "japanese_required": "N4",
        "education_required": "trung_cap",
        "experience_min": 0,
        "age_min": 20,
        "age_max": 35,
        "gender_pref": "khong_yeu_cau",
        "salary_min": 188000,
        "salary_max": 202000,
        "allowances": ["Hỗ trợ ký túc xá", "Phụ cấp đi lại"],
        "cost_total_vnd": 100_000_000,
        "interview_in_days": 42,
        "departure_expected": "2027-05",
        "highlights": ["Đang tạm dừng nhận hồ sơ"],
        "description": "Đơn tạm dừng theo yêu cầu của đối tác, dùng để kiểm tra đơn tạm dừng không lọt ra website.",
        "status": "paused",
        "published": True,
        "internal_note": "Đơn mẫu: tạm dừng nhưng cờ công khai vẫn bật, phải bị lọc ở tầng truy vấn.",
    },
]
